export const FIELD_LABELS: Record<string, string> = {
  'personal.fullName': 'Full name',
  'personal.gender': 'Gender',
  'personal.dateOfBirth': 'Date of birth',
  'personal.age': 'Age',
  'personal.height': 'Height',
  'personal.religion': 'Religion',
  'personal.caste': 'Caste',
  'personal.motherTongue': 'Mother tongue',
  'personal.maritalStatus': 'Marital status',
  'personal.location': 'Location',
  'education.highestEducation': 'Education',
  'education.institution': 'Institution',
  'education.additionalEducation': 'Additional education',
  'career.profession': 'Profession',
  'career.company': 'Company',
  'career.income': 'Income',
  'career.workLocation': 'Work location',
  'family.fatherName': "Father's name",
  'family.fatherOccupation': "Father's occupation",
  'family.motherName': "Mother's name",
  'family.motherOccupation': "Mother's occupation",
  'family.siblings': 'Siblings',
  'family.familyLocation': 'Family location',
  'about.aboutMe': 'About',
  'about.hobbies': 'Hobbies',
  'about.lifestyle': 'Lifestyle',
  'contact.contactName': 'Contact name',
  'contact.phone': 'Phone',
  'contact.email': 'Email',
  'contact.address': 'Address',
};
